#!/bin/bash
#/##############################################################################
 #
 # main.sh - Call all scripts and sent data to the server.
 #
 # Program: ctracker
 # License: GPL
 #
 # First Written:   2012
 # Copyright (C) 2012-2014 - Author: Matheus SantAna Lima <matheusslima@yahoo.com.br>
 #
 # Description:
 #
 # License:
 #
 #   This program is free software: you can redistribute it and/or modify
 #   it under the terms of the GNU General Public License as published by
 #   the Free Software Foundation, either version 3 of the License, or
 #   (at your option) any later version.

 #   This program is distributed in the hope that it will be useful,
 #   but WITHOUT ANY WARRANTY; without even the implied warranty of
 #   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 #   GNU General Public License for more details.

 #   You should have received a copy of the GNU General Public License
 #   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 #
 #############################################################################/


#reading config file
. info.conf;

#lock mutex

if mkdir /tmp/ctracker.lock; then

	for (( ; ; ))
	do

		data=$(./vmstat_tracker.sh);
		data="$data

		 \"InstanceToken\":\"$ITOKEN\"}
		";
		curl --data 'data='"$data" $SERVERURL

		sleep $TIMESAMPLES
	done
else

	echo "Lock failed - exit" >&2
	exit 1
fi
