<?php
/******************************************************************************
 *
 * form.php - Used to display forms for new users, instances, etc. Also handles client-side validation.
 *
 * Program: ctracker
 * License: GPL
 *
 * First Written:  2012
 * Copyright (C) 2012-2013 - Author: Matheus SantAna Lima <matheusslima@yahoo.com.br>
 *
 * Description:
 *
 * License:
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.

 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.

 *   You should have received a copy of the GNU General Public License
 *   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 *****************************************************************************/
//include_once "../functions.php";
//$tp = formatData($_GET['tp']);

$tp = $_GET['tp'];?>


<?
if (strcmp($tp, "Register") == 0) {
	$action = "index.php?pg=add";
echo '          <p style="padding: 10px;"> Register </p>';

}
elseif (strcmp($tp, "add-alert") == 0) {
        $action = "index.php?pg=../add";

}
elseif (strcmp($tp, "add-server") == 0) {
	$action = "index.php?pg=../add";
}
?>


<?if (strcmp($tp, "Register") == 0) {?>
    <script language="javascript">
        function validate (form){
		if (form.email.value.indexOf("@") == -1 || form.email.value.lastIndexOf(".") == -1) {
		alert("Not a valid email address");
				form.email.focus();
				return false;
		}

		if (form.email.value.lastIndexOf(".") < form.email.value.indexOf("@")) {
		alert("Not a valid email address");
				form.email.focus();
				return false;
		}

		if (form.email.value.lastIndexOf(".") - form.email.value.indexOf("@") == 1) {
		alert("Not a valid email address");
				form.email.focus();
				return false;
		}

            if(form.password.value==""){
                alert("You must enter your password.");
                form.password.focus();
                return false;
            }

		if(form.password2.value != form.password.value){
	                alert("Passwords don't match.");
        	        form.password2.focus();
                	return false;
		}


            return true;
        }
</script>


<?}?>
<form method="post" name="form" action="<?php echo $action; ?>" onSubmit="return validate(this)"<?php if (isset($enctype))
    echo " enctype=\"" . $enctype . "\""; ?>>
<?
if (strcmp($tp, "Register") == 0) {
?>

		<label for="name">Email:</label>
		
		<input type="name" name="email">
		<label for="password">Password:</label>
		<input type="password" name="password">
		
		<label for="password2">Repeat password:</label>
		<input type="password" name="password2">
	

		<div id="lower">
		
		<input type="submit" name = "submit" value="Registrar">
		<input type="hidden" name="tp" value="signup"/>
		
		</div>
		
<?
}elseif (strcmp($tp, "add-server") == 0) {
?>

		<label for="name">Name:</label>
		
		<input type="name" style="border-color: #555555 #CCCCCC #CCCCCC #555555;
    border-style: solid;
    border-width: 1px;
    color: #333333;
    padding: 1px;
    width: 150px;" name="name" required>

		<style type="text/css">
.add-server {
	-moz-box-shadow:inset 0px 1px 0px 0px #ffffff;
	-webkit-box-shadow:inset 0px 1px 0px 0px #ffffff;
	box-shadow:inset 0px 1px 0px 0px #ffffff;
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #ededed), color-stop(1, #dfdfdf) );
	background:-moz-linear-gradient( center top, #ededed 5%, #dfdfdf 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#ededed', endColorstr='#dfdfdf');
	background-color:#ededed;
	-moz-border-radius:6px;
	-webkit-border-radius:6px;
	border-radius:6px;
	border:1px solid #dcdcdc;
	display:inline-block;
	color:#777777;
	font-family:arial;
/*	font-size:15px;*/
	font-weight:bold;
	padding:2px 20px;
	text-decoration:none;
	text-shadow:1px 1px 0px #ffffff;
}.add-server:hover {
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #dfdfdf), color-stop(1, #ededed) );
	background:-moz-linear-gradient( center top, #dfdfdf 5%, #ededed 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#dfdfdf', endColorstr='#ededed');
	background-color:#dfdfdf;
}.add-server:active {
	position:relative;
	top:1px;
}
/* This imageless css button was generated by CSSButtonGenerator.com */
</style>

		<input type="submit" class="add-server" name = "submit" value="Add">
		<input type="hidden" name="tp" value="add-server"/>
		
</div>

<?
}elseif (strcmp($tp, "add-alert") == 0) {

        include "../alert/options.php";

?>
<?}?>
		</form>


