#!/bin/bash
#/#############################################################################
#
 #
 # vmstat_tracker.sh - Get OS data from vmstat command and generate JSON output
 #
 # Program: ctracker
 # License: GPL
 #
 # First Written:   2012
 # Copyright (C) 2012-2013 - Author: Matheus SantAna Lima <matheusslima@yahoo.com.br>
 #
 # Description:
 #
 # License:
 #
 #   This program is free software: you can redistribute it and/or modify
 #   it under the terms of the GNU General Public License as published by
 #   the Free Software Foundation, either version 3 of the License, or
 #   (at your option) any later version.

 #   This program is distributed in the hope that it will be useful,
 #   but WITHOUT ANY WARRANTY; without even the implied warranty of
 #   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 #   GNU General Public License for more details.

 #   You should have received a copy of the GNU General Public License
 #   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 #
 #############################################################################/

# chkconfig: 345 20 80
# description: ctracker init script

# Source function library.
. /etc/init.d/functions

start() {
# code to start app comes here 
	echo "Starting ctracker...";
	ctracker
}

stop() {
# code to stop app comes here 
	echo "Stopping ctracker"
	killall ctracker-main
	rm -rf /tmp/ctracker.lock
}

status() {

	pid=$(ps aux | grep ctracker-main | grep -v grep | column -t | awk '{print $2}');
	if [[ ! -z $pid ]]
	then
		echo "ctracker($pid) is running..."
	else
		echo "ctracker is not running..."
	fi

}

case "$1" in 
	start)
		start
		;;
	stop)
		stop
		;;
	status)

		status
		;;
	restart)
		stop
		start
		;;
	*)
echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0
